name: Build

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Build solution
        run: dotnet build -c Debug

      # - name: Publish
      #   run: dotnet publish -c Release --no-build --no-restore

      # - name: Run tests
      #   run: dotnet test -c Debug --no-build --no-restore
